### PR TITLE
Fix app navigation menu, closes #49

### LINKED ISSUE #49: Deletion countdown cancelation not working since the last popover unification
Since nextcloud/server#3024

- [ ] Clicking the cancel button still delete the task
- [ ] Design is broken
- [ ] Does not fit the guidelines ⚠️

### PR DESCRIPTION
**Pull request by raimund-schluessler**
@skjnldsv Could you have a look here, please? I fixed the app navigation menu including the delete countdown.

<strike>The sortorder dropdown list needs some attention now, but I will do this in a follow up PR.</strike>

I decided to fix the sortorder dropdown here too. Should be all good now.

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
@skjnldsv would be awesome, if you could have a look :smile:

File: templates/main.php [hunk 1]
```diff
@@ -167,46 +167,46 @@ class="collection"
             <div class="app-navigation-entry-menu bubble sortorder-dropdown">
```
Comment (skjnldsv) [inline templates/main.php]: This is NOT a `app-navigation-entry-menu`, we're in the content, this should be a popovermenu 😉 
Though this should roughly be similar, changing the class should be enough :)

The menu content on the other hand, seems to be broken (triangle), so since we're working on this, maybe fix this too? 😄

Comment (skjnldsv) [inline templates/main.php]: If you want to work on this in another pr, I will change my review to approved to merge this fast! ;)

Comment (raimund-schluessler) [inline templates/main.php]: I created an issue: https://github.com/nextcloud/tasks/issues/57

Comment (skjnldsv) [inline templates/main.php]: The click on menu is broken too, this is not just the guidelines 😃 
When you select a sort option, you can't click the button again (or with a lot of difficulties)

**Comment by raimund-schluessler** [comment]
Great, thanks for reviewing. Will tackle the popover problem asap.

File: templates/main.php (hunk 1 above)
Comment (raimund-schluessler) [inline templates/main.php]: Hm, I never considered this a bug. But I am ok with keeping the menu open after clicking the popover.

Comment (skjnldsv) [inline templates/main.php]: No no, Im talking about the button, not the menu :)

Comment (raimund-schluessler) [inline templates/main.php]: Sorry, I don't get what you mean. Clicking on the sort-order dropdown button opens the menu, clicking it again, closes it. When I click inside the popover, a sorttype is selected and the menu is closed. What is wrong about that? 😕

Comment (skjnldsv) [inline templates/main.php]: Ahaha, sorry, you're right I'm not clear!
When you click the button, the popover opens, you can select an option and it closes right away, which is perfect!
BUT, when after that you try to click te button again, it doesnt work. You need to click just under the icon. It doesn't work after that.

Comment (raimund-schluessler) [inline templates/main.php]: Hm, I can't reproduce this behavior. After selecting an option I can open and close the menu just fine. It behaves the same as before. Could you maybe create an issue for that and tell me which browser you use?
