### PR TITLE
Unify task deletion undo

### LINKED ISSUE #1408: prompt to delete a task or provide undo delete
### Steps to reproduce
1. Create task
2. Click delete task (unintentionally).

### Expected behaviour
Prompt to delete the task if not reversible, or provide either a trash where deleted tasks can be restored from, or undo delete feature. If any of these features are implemented, they are difficult to find in the UI.

### Actual behaviour
Task is deleted immediately and permanently.

### Server configuration

**Operating system**: 
Debian 10

**Web server:**
NginX

**Database:**
Postgresql

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
19.0.6

**Tasks version:** (see Nextcloud apps page)
0.13.6

**Updated from an older Nextcloud or fresh install:**

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/nextcloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

### PR DESCRIPTION
**Pull request by raimund-schluessler**
This PR unifies the task deletion undo, so that an undo action also appears in the AppSidebar. Closes #1408.

Deleting a task now looks like this:
delete

### CODE REVIEW

File: src/components/TaskBody.vue [hunk 1]
```diff
@@ -26,7 +26,7 @@ License along with this library.  If not, see <http://www.gnu.org/licenses/>.
 		:task-id="task.uri"
 		:class="{
 			'task-item--closed': task.closed,
-			'task-item--deleted': !!deleteTimeout,
+			'task-item--deleted': !!task.deleteCountdown,
```
Comment (raimund-schluessler) [inline src/components/TaskBody.vue:29]: Should be compared to `null`, otherwise it will break if deleteCountdown is `0`.

File: src/store/tasks.js [hunk 2]
```diff
@@ -719,7 +743,7 @@ const actions = {
 	 * @param {Task} data.task The task to delete
 	 * @param {Boolean} [data.dav = true] Trigger a dav deletion
 	 */
-	async deleteTask(context, { task, dav = true }) {
+	async deleteTaskReally(context, { task, dav = true }) {
```
Comment (raimund-schluessler) [inline src/store/tasks.js:746]: function naming needs to be fixed.

File: src/store/tasks.js [hunk 3]
```diff
@@ -734,10 +758,21 @@ const actions = {
 			const parent = context.getters.getTaskByUid(task.related)
 			context.commit('deleteTaskFromParent', { task, parent })
 			context.commit('deleteTaskFromCalendar', task)
+			context.commit('cancelTaskDeletion', { task })
+			// If the task is open in the sidebar, close the sidebar
+			// TODO: Also check if a descendant is open
```
Comment (raimund-schluessler) [inline src/store/tasks.js:763]: Not necessary to check for descendants. They will be deleted as well and the sidebar gets closed.
